Improvements to the chapter screen
OH296/ChapterMaster pull request #17
Opened 2024-03-22 10:36 UTC by EttyKitty

A new tiny function to draw bold text.
Rename "Chapter Master" into "Chapter Command" and display current Honor Guard count. Some text visibility improvements and other minor edits.

2024-03-23 18:15 UTC, OH296 requested changes
Looking really good, makes some good improvements. One major problem regarding script sequences with a initialise_custom and a few minor suggestions

2024-03-23 18:15 UTC, OH296 commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
initialise custom is not run when loading a save so having this here will mean the enum data is unavailable on load and will cause an error, best to define the enum outside of the scope of a function then it will defiantly be global

2024-03-23 18:15 UTC, OH296 commented on scripts/scr_management/scr_management.gml
>  	    for (var i = 1; i <= 200; i++) {
```suggestion
	    for (var i = 1; i <= 200; i++) {
	         unit = fetch_unit([0,i]);
```
move to using the modern syntax wherever possible when editing a specific code portion

2024-03-23 18:15 UTC, OH296 commented on scripts/scr_management/scr_management.gml
>  	    for (var i = 1; i <= 200; i++) {
same here move to modern syntax

2024-03-23 18:15 UTC, OH296 commented on scripts/scr_management/scr_management.gml
>  	    for (var i = 1; i <= 200; i++) {
modern syntax

2024-03-23 18:15 UTC, OH296 commented on scripts/scr_management/scr_management.gml
> +			nam[2] = role_names[Role.CHAPLAIN];
neato

2024-03-24 00:43 UTC, EttyKitty commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
where should I define it? in obj_controller creation event?

2024-03-24 00:47 UTC, OH296 commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
just define it in theinitialise custom script but outside of the initialise_custom function then it will be defined globally  as enums do not need to be defined in any particular scope

2024-03-24 01:42 UTC, EttyKitty commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
isn't it a bad practice to have something defined in the script file but not in the script scope? is there no better file for this?

2024-03-24 01:45 UTC, EttyKitty commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
I can put it into obj_ini create event. that's where this function is called. before the if check, of course.

2024-03-24 19:47 UTC, OH296 commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
i wouldn't want a static stored in any place but a script file personally if you store it in an obj event it's creation is tied to that object event, gml automatically loads all scripts on game start so better to have it in a script,  from a practicality argument it's near where the other data of a similar kind is stored and arguably thats what a script is for clumping similar data. My main concern is it goes somewhere that won't cause an error. and tied to any object has the capacity to cause an error

2024-03-24 19:49 UTC, merged

2024-03-25 03:40 UTC, EttyKitty commented on scripts/scr_initialize_custom/scr_initialize_custom.gml
> +
>gml automatically loads all scripts on game start so better to have it in a script,
ooh, I didn't know that. makes sense now.